const spellUrls = {
  "Abi-Dalzim's Horrid Wilting": "https://5e.tools/spells.html#abi-dalzim%27s%20horrid%20wilting_xge",
  "Absorb Elements": "https://5e.tools/spells.html#absorb%20elements_xge",
  "Acid Splash": "https://5e.tools/spells.html#acid%20splash_phb",
  "Aganazzar's Scorcher": "https://5e.tools/spells.html#aganazzar%27s%20scorcher_xge",
  "Aid": "https://5e.tools/spells.html#aid_phb",
  "Air Bubble": "https://5e.tools/spells.html#air%20bubble_aag",
  "Alarm": "https://5e.tools/spells.html#alarm_phb",
  "Alter Self": "https://5e.tools/spells.html#alter%20self_phb",
  "Animal Friendship": "https://5e.tools/spells.html#animal%20friendship_phb",
  "Animal Messenger": "https://5e.tools/spells.html#animal%20messenger_phb",
  "Animal Shapes": "https://5e.tools/spells.html#animal%20shapes_phb",
  "Animate Dead": "https://5e.tools/spells.html#animate%20dead_phb",
  "Animate Objects": "https://5e.tools/spells.html#animate%20objects_phb",
  "Antagonize": "https://5e.tools/spells.html#antagonize_bmt",
  "Antilife Shell": "https://5e.tools/spells.html#antilife%20shell_phb",
  "Antimagic Field": "https://5e.tools/spells.html#antimagic%20field_phb",
  "Antipathy/Sympathy": "https://5e.tools/spells.html#antipathy/sympathy_phb",
  "Arcane Eye": "https://5e.tools/spells.html#arcane%20eye_phb",
  "Arcane Gate": "https://5e.tools/spells.html#arcane%20gate_phb",
  "Arcane Lock": "https://5e.tools/spells.html#arcane%20lock_phb",
  "Armor of Agathys": "https://5e.tools/spells.html#armor%20of%20agathys_phb",
  "Arms of Hadar": "https://5e.tools/spells.html#arms%20of%20hadar_phb",
  "Ashardalon's Stride": "https://5e.tools/spells.html#ashardalon%27s%20stride_ftd",
  "Astral Projection": "https://5e.tools/spells.html#astral%20projection_phb",
  "Augury": "https://5e.tools/spells.html#augury_phb",
  "Aura of Life": "https://5e.tools/spells.html#aura%20of%20life_phb",
  "Aura of Purity": "https://5e.tools/spells.html#aura%20of%20purity_phb",
  "Aura of Vitality": "https://5e.tools/spells.html#aura%20of%20vitality_phb",
  "Awaken": "https://5e.tools/spells.html#awaken_phb",
  "Bane": "https://5e.tools/spells.html#bane_phb",
  "Banishing Smite": "https://5e.tools/spells.html#banishing%20smite_phb",
  "Banishment": "https://5e.tools/spells.html#banishment_phb",
  "Barkskin": "https://5e.tools/spells.html#barkskin_phb",
  "Beacon of Hope": "https://5e.tools/spells.html#beacon%20of%20hope_phb",
  "Beast Bond": "https://5e.tools/spells.html#beast%20bond_xge",
  "Beast Sense": "https://5e.tools/spells.html#beast%20sense_phb",
  "Bestow Curse": "https://5e.tools/spells.html#bestow%20curse_phb",
  "Bigby's Hand": "https://5e.tools/spells.html#bigby%27s%20hand_phb",
  "Blade Barrier": "https://5e.tools/spells.html#blade%20barrier_phb",
  "Blade of Disaster": "https://5e.tools/spells.html#blade%20of%20disaster_tce",
  "Blade Ward": "https://5e.tools/spells.html#blade%20ward_phb",
  "Bless": "https://5e.tools/spells.html#bless_phb",
  "Blight": "https://5e.tools/spells.html#blight_phb",
  "Blinding Smite": "https://5e.tools/spells.html#blinding%20smite_phb",
  "Blindness/Deafness": "https://5e.tools/spells.html#blindness/deafness_phb",
  "Blink": "https://5e.tools/spells.html#blink_phb",
  "Blur": "https://5e.tools/spells.html#blur_phb",
  "Bones of the Earth": "https://5e.tools/spells.html#bones%20of%20the%20earth_xge",
  "Booming Blade": "https://5e.tools/spells.html#booming%20blade_tce",
  "Borrowed Knowledge": "https://5e.tools/spells.html#borrowed%20knowledge_scc",
  "Branding Smite": "https://5e.tools/spells.html#branding%20smite_phb",
  "Burning Hands": "https://5e.tools/spells.html#burning%20hands_phb",
  "Call Lightning": "https://5e.tools/spells.html#call%20lightning_phb",
  "Calm Emotions": "https://5e.tools/spells.html#calm%20emotions_phb",
  "Catapult": "https://5e.tools/spells.html#catapult_xge",
  "Catnap": "https://5e.tools/spells.html#catnap_xge",
  "Cause Fear": "https://5e.tools/spells.html#cause%20fear_xge",
  "Ceremony": "https://5e.tools/spells.html#ceremony_xge",
  "Chain Lightning": "https://5e.tools/spells.html#chain%20lightning_phb",
  "Chaos Bolt": "https://5e.tools/spells.html#chaos%20bolt_xge",
  "Charm Monster": "https://5e.tools/spells.html#charm%20monster_xge",
  "Charm Person": "https://5e.tools/spells.html#charm%20person_phb",
  "Chill Touch": "https://5e.tools/spells.html#chill%20touch_phb",
  "Chromatic Orb": "https://5e.tools/spells.html#chromatic%20orb_phb",
  "Circle of Death": "https://5e.tools/spells.html#circle%20of%20death_phb",
  "Circle of Power": "https://5e.tools/spells.html#circle%20of%20power_phb",
  "Clairvoyance": "https://5e.tools/spells.html#clairvoyance_phb",
  "Clone": "https://5e.tools/spells.html#clone_phb",
  "Cloud of Daggers": "https://5e.tools/spells.html#cloud%20of%20daggers_phb",
  "Cloudkill": "https://5e.tools/spells.html#cloudkill_phb",
  "Color Spray": "https://5e.tools/spells.html#color%20spray_phb",
  "Command": "https://5e.tools/spells.html#command_phb",
  "Commune": "https://5e.tools/spells.html#commune_phb",
  "Commune with Nature": "https://5e.tools/spells.html#commune%20with%20nature_phb",
  "Compelled Duel": "https://5e.tools/spells.html#compelled%20duel_phb",
  "Comprehend Languages": "https://5e.tools/spells.html#comprehend%20languages_phb",
  "Compulsion": "https://5e.tools/spells.html#compulsion_phb",
  "Cone of Cold": "https://5e.tools/spells.html#cone%20of%20cold_phb",
  "Confusion": "https://5e.tools/spells.html#confusion_phb",
  "Conjure Animals": "https://5e.tools/spells.html#conjure%20animals_phb",
  "Conjure Barrage": "https://5e.tools/spells.html#conjure%20barrage_phb",
  "Conjure Celestial": "https://5e.tools/spells.html#conjure%20celestial_phb",
  "Conjure Elemental": "https://5e.tools/spells.html#conjure%20elemental_phb",
  "Conjure Fey": "https://5e.tools/spells.html#conjure%20fey_phb",
  "Conjure Minor Elementals": "https://5e.tools/spells.html#conjure%20minor%20elementals_phb",
  "Conjure Volley": "https://5e.tools/spells.html#conjure%20volley_phb",
  "Conjure Woodland Beings": "https://5e.tools/spells.html#conjure%20woodland%20beings_phb",
  "Contact Other Plane": "https://5e.tools/spells.html#contact%20other%20plane_phb",
  "Contagion": "https://5e.tools/spells.html#contagion_phb",
  "Contingency": "https://5e.tools/spells.html#contingency_phb",
  "Continual Flame": "https://5e.tools/spells.html#continual%20flame_phb",
  "Control Flames": "https://5e.tools/spells.html#control%20flames_xge",
  "Control Water": "https://5e.tools/spells.html#control%20water_phb",
  "Control Weather": "https://5e.tools/spells.html#control%20weather_phb",
  "Control Winds": "https://5e.tools/spells.html#control%20winds_xge",
  "Cordon of Arrows": "https://5e.tools/spells.html#cordon%20of%20arrows_phb",
  "Counterspell": "https://5e.tools/spells.html#counterspell_phb",
  "Create Bonfire": "https://5e.tools/spells.html#create%20bonfire_xge",
  "Create Food and Water": "https://5e.tools/spells.html#create%20food%20and%20water_phb",
  "Create Homunculus": "https://5e.tools/spells.html#create%20homunculus_xge",
  "Create Magen": "https://5e.tools/spells.html#create%20magen_idrotf",
  "Create or Destroy Water": "https://5e.tools/spells.html#create%20or%20destroy%20water_phb",
  "Create Spelljamming Helm": "https://5e.tools/spells.html#create%20spelljamming%20helm_aag",
  "Create Undead": "https://5e.tools/spells.html#create%20undead_phb",
  "Creation": "https://5e.tools/spells.html#creation_phb",
  "Crown of Madness": "https://5e.tools/spells.html#crown%20of%20madness_phb",
  "Crown of Stars": "https://5e.tools/spells.html#crown%20of%20stars_xge",
  "Crusader's Mantle": "https://5e.tools/spells.html#crusader%27s%20mantle_phb",
  "Cure Wounds": "https://5e.tools/spells.html#cure%20wounds_phb",
  "Dancing Lights": "https://5e.tools/spells.html#dancing%20lights_phb",
  "Danse Macabre": "https://5e.tools/spells.html#danse%20macabre_xge",
  "Darkness": "https://5e.tools/spells.html#darkness_phb",
  "Darkvision": "https://5e.tools/spells.html#darkvision_phb",
  "Dawn": "https://5e.tools/spells.html#dawn_xge",
  "Daylight": "https://5e.tools/spells.html#daylight_phb",
  "Death Ward": "https://5e.tools/spells.html#death%20ward_phb",
  "Delayed Blast Fireball": "https://5e.tools/spells.html#delayed%20blast%20fireball_phb",
  "Demiplane": "https://5e.tools/spells.html#demiplane_phb",
  "Destructive Wave": "https://5e.tools/spells.html#destructive%20wave_phb",
  "Detect Evil and Good": "https://5e.tools/spells.html#detect%20evil%20and%20good_phb",
  "Detect Magic": "https://5e.tools/spells.html#detect%20magic_phb",
  "Detect Poison and Disease": "https://5e.tools/spells.html#detect%20poison%20and%20disease_phb",
  "Detect Thoughts": "https://5e.tools/spells.html#detect%20thoughts_phb",
  "Dimension Door": "https://5e.tools/spells.html#dimension%20door_phb",
  "Disguise Self": "https://5e.tools/spells.html#disguise%20self_phb",
  "Disintegrate": "https://5e.tools/spells.html#disintegrate_phb",
  "Dispel Evil and Good": "https://5e.tools/spells.html#dispel%20evil%20and%20good_phb",
  "Dispel Magic": "https://5e.tools/spells.html#dispel%20magic_phb",
  "Dissonant Whispers": "https://5e.tools/spells.html#dissonant%20whispers_phb",
  "Distort Value": "https://5e.tools/spells.html#distort%20value_ai",
  "Divination": "https://5e.tools/spells.html#divination_phb",
  "Divine Favor": "https://5e.tools/spells.html#divine%20favor_phb",
  "Divine Word": "https://5e.tools/spells.html#divine%20word_phb",
  "Dominate Beast": "https://5e.tools/spells.html#dominate%20beast_phb",
  "Dominate Monster": "https://5e.tools/spells.html#dominate%20monster_phb",
  "Dominate Person": "https://5e.tools/spells.html#dominate%20person_phb",
  "Draconic Transformation": "https://5e.tools/spells.html#draconic%20transformation_ftd",
  "Dragon's Breath": "https://5e.tools/spells.html#dragon%27s%20breath_xge",
  "Drawmij's Instant Summons": "https://5e.tools/spells.html#drawmij%27s%20instant%20summons_phb",
  "Dream": "https://5e.tools/spells.html#dream_phb",
  "Dream of the Blue Veil": "https://5e.tools/spells.html#dream%20of%20the%20blue%20veil_tce",
  "Druid Grove": "https://5e.tools/spells.html#druid%20grove_xge",
  "Druidcraft": "https://5e.tools/spells.html#druidcraft_phb",
  "Dust Devil": "https://5e.tools/spells.html#dust%20devil_xge",
  "Earth Tremor": "https://5e.tools/spells.html#earth%20tremor_xge",
  "Earthbind": "https://5e.tools/spells.html#earthbind_xge",
  "Earthquake": "https://5e.tools/spells.html#earthquake_phb",
  "Eldritch Blast": "https://5e.tools/spells.html#eldritch%20blast_phb",
  "Elemental Bane": "https://5e.tools/spells.html#elemental%20bane_xge",
  "Elemental Weapon": "https://5e.tools/spells.html#elemental%20weapon_phb",
  "Encode Thoughts": "https://5e.tools/spells.html#encode%20thoughts_ggr",
  "Enemies Abound": "https://5e.tools/spells.html#enemies%20abound_xge",
  "Enervation": "https://5e.tools/spells.html#enervation_xge",
  "Enhance Ability": "https://5e.tools/spells.html#enhance%20ability_phb",
  "Enlarge/Reduce": "https://5e.tools/spells.html#enlarge/reduce_phb",
  "Ensnaring Strike": "https://5e.tools/spells.html#ensnaring%20strike_phb",
  "Entangle": "https://5e.tools/spells.html#entangle_phb",
  "Enthrall": "https://5e.tools/spells.html#enthrall_phb",
  "Erupting Earth": "https://5e.tools/spells.html#erupting%20earth_xge",
  "Etherealness": "https://5e.tools/spells.html#etherealness_phb",
  "Evard's Black Tentacles": "https://5e.tools/spells.html#evard%27s%20black%20tentacles_phb",
  "Expeditious Retreat": "https://5e.tools/spells.html#expeditious%20retreat_phb",
  "Eyebite": "https://5e.tools/spells.html#eyebite_phb",
  "Fabricate": "https://5e.tools/spells.html#fabricate_phb",
  "Faerie Fire": "https://5e.tools/spells.html#faerie%20fire_phb",
  "False Life": "https://5e.tools/spells.html#false%20life_phb",
  "Far Step": "https://5e.tools/spells.html#far%20step_xge",
  "Fast Friends": "https://5e.tools/spells.html#fast%20friends_ai",
  "Fear": "https://5e.tools/spells.html#fear_phb",
  "Feather Fall": "https://5e.tools/spells.html#feather%20fall_phb",
  "Feeblemind": "https://5e.tools/spells.html#feeblemind_phb",
  "Feign Death": "https://5e.tools/spells.html#feign%20death_phb",
  "Find Familiar": "https://5e.tools/spells.html#find%20familiar_phb",
  "Find Greater Steed": "https://5e.tools/spells.html#find%20greater%20steed_xge",
  "Find Steed": "https://5e.tools/spells.html#find%20steed_phb",
  "Find the Path": "https://5e.tools/spells.html#find%20the%20path_phb",
  "Find Traps": "https://5e.tools/spells.html#find%20traps_phb",
  "Finger of Death": "https://5e.tools/spells.html#finger%20of%20death_phb",
  "Fire Bolt": "https://5e.tools/spells.html#fire%20bolt_phb",
  "Fire Shield": "https://5e.tools/spells.html#fire%20shield_phb",
  "Fire Storm": "https://5e.tools/spells.html#fire%20storm_phb",
  "Fireball": "https://5e.tools/spells.html#fireball_phb",
  "Fizban's Platinum Shield": "https://5e.tools/spells.html#fizban%27s%20platinum%20shield_ftd",
  "Flame Arrows": "https://5e.tools/spells.html#flame%20arrows_xge",
  "Flame Blade": "https://5e.tools/spells.html#flame%20blade_phb",
  "Flame Strike": "https://5e.tools/spells.html#flame%20strike_phb",
  "Flaming Sphere": "https://5e.tools/spells.html#flaming%20sphere_phb",
  "Flesh to Stone": "https://5e.tools/spells.html#flesh%20to%20stone_phb",
  "Fly": "https://5e.tools/spells.html#fly_phb",
  "Fog Cloud": "https://5e.tools/spells.html#fog%20cloud_phb",
  "Forbiddance": "https://5e.tools/spells.html#forbiddance_phb",
  "Forcecage": "https://5e.tools/spells.html#forcecage_phb",
  "Foresight": "https://5e.tools/spells.html#foresight_phb",
  "Freedom of Movement": "https://5e.tools/spells.html#freedom%20of%20movement_phb",
  "Friends": "https://5e.tools/spells.html#friends_phb",
  "Frost Fingers": "https://5e.tools/spells.html#frost%20fingers_idrotf",
  "Frostbite": "https://5e.tools/spells.html#frostbite_xge",
  "Gaseous Form": "https://5e.tools/spells.html#gaseous%20form_phb",
  "Gate": "https://5e.tools/spells.html#gate_phb",
  "Gate Seal": "https://5e.tools/spells.html#gate%20seal_sato",
  "Geas": "https://5e.tools/spells.html#geas_phb",
  "Gentle Repose": "https://5e.tools/spells.html#gentle%20repose_phb",
  "Giant Insect": "https://5e.tools/spells.html#giant%20insect_phb",
  "Gift of Gab": "https://5e.tools/spells.html#gift%20of%20gab_ai",
  "Glibness": "https://5e.tools/spells.html#glibness_phb",
  "Globe of Invulnerability": "https://5e.tools/spells.html#globe%20of%20invulnerability_phb",
  "Glyph of Warding": "https://5e.tools/spells.html#glyph%20of%20warding_phb",
  "Goodberry": "https://5e.tools/spells.html#goodberry_phb",
  "Grasping Vine": "https://5e.tools/spells.html#grasping%20vine_phb",
  "Grease": "https://5e.tools/spells.html#grease_phb",
  "Greater Invisibility": "https://5e.tools/spells.html#greater%20invisibility_phb",
  "Greater Restoration": "https://5e.tools/spells.html#greater%20restoration_phb",
  "Green-Flame Blade": "https://5e.tools/spells.html#green-flame%20blade_tce",
  "Guardian of Faith": "https://5e.tools/spells.html#guardian%20of%20faith_phb",
  "Guardian of Nature": "https://5e.tools/spells.html#guardian%20of%20nature_xge",
  "Guards and Wards": "https://5e.tools/spells.html#guards%20and%20wards_phb",
  "Guidance": "https://5e.tools/spells.html#guidance_phb",
  "Guiding Bolt": "https://5e.tools/spells.html#guiding%20bolt_phb",
  "Gust": "https://5e.tools/spells.html#gust_xge",
  "Gust of Wind": "https://5e.tools/spells.html#gust%20of%20wind_phb",
  "Hail of Thorns": "https://5e.tools/spells.html#hail%20of%20thorns_phb",
  "Hallow": "https://5e.tools/spells.html#hallow_phb",
  "Hallucinatory Terrain": "https://5e.tools/spells.html#hallucinatory%20terrain_phb",
  "Harm": "https://5e.tools/spells.html#harm_phb",
  "Haste": "https://5e.tools/spells.html#haste_phb",
  "Heal": "https://5e.tools/spells.html#heal_phb",
  "Healing Spirit": "https://5e.tools/spells.html#healing%20spirit_xge",
  "Healing Word": "https://5e.tools/spells.html#healing%20word_phb",
  "Heat Metal": "https://5e.tools/spells.html#heat%20metal_phb",
  "Hellish Rebuke": "https://5e.tools/spells.html#hellish%20rebuke_phb",
  "Heroes' Feast": "https://5e.tools/spells.html#heroes%27%20feast_phb",
  "Heroism": "https://5e.tools/spells.html#heroism_phb",
  "Hex": "https://5e.tools/spells.html#hex_phb",
  "Hold Monster": "https://5e.tools/spells.html#hold%20monster_phb",
  "Hold Person": "https://5e.tools/spells.html#hold%20person_phb",
  "Holy Aura": "https://5e.tools/spells.html#holy%20aura_phb",
  "Holy Weapon": "https://5e.tools/spells.html#holy%20weapon_xge",
  "Hunger of Hadar": "https://5e.tools/spells.html#hunger%20of%20hadar_phb",
  "Hunter's Mark": "https://5e.tools/spells.html#hunter%27s%20mark_phb",
  "Hypnotic Pattern": "https://5e.tools/spells.html#hypnotic%20pattern_phb",
  "Ice Knife": "https://5e.tools/spells.html#ice%20knife_xge",
  "Ice Storm": "https://5e.tools/spells.html#ice%20storm_phb",
  "Identify": "https://5e.tools/spells.html#identify_phb",
  "Illusory Dragon": "https://5e.tools/spells.html#illusory%20dragon_xge",
  "Illusory Script": "https://5e.tools/spells.html#illusory%20script_phb",
  "Immolation": "https://5e.tools/spells.html#immolation_xge",
  "Imprisonment": "https://5e.tools/spells.html#imprisonment_phb",
  "Incendiary Cloud": "https://5e.tools/spells.html#incendiary%20cloud_phb",
  "Incite Greed": "https://5e.tools/spells.html#incite%20greed_ai",
  "Infernal Calling": "https://5e.tools/spells.html#infernal%20calling_xge",
  "Infestation": "https://5e.tools/spells.html#infestation_xge",
  "Inflict Wounds": "https://5e.tools/spells.html#inflict%20wounds_phb",
  "Insect Plague": "https://5e.tools/spells.html#insect%20plague_phb",
  "Intellect Fortress": "https://5e.tools/spells.html#intellect%20fortress_tce",
  "Investiture of Flame": "https://5e.tools/spells.html#investiture%20of%20flame_xge",
  "Investiture of Ice": "https://5e.tools/spells.html#investiture%20of%20ice_xge",
  "Investiture of Stone": "https://5e.tools/spells.html#investiture%20of%20stone_xge",
  "Investiture of Wind": "https://5e.tools/spells.html#investiture%20of%20wind_xge",
  "Invisibility": "https://5e.tools/spells.html#invisibility_phb",
  "Invulnerability": "https://5e.tools/spells.html#invulnerability_xge",
  "Jim's Glowing Coin": "https://5e.tools/spells.html#jim%27s%20glowing%20coin_ai",
  "Jim's Magic Missile": "https://5e.tools/spells.html#jim%27s%20magic%20missile_ai",
  "Jump": "https://5e.tools/spells.html#jump_phb",
  "Kinetic Jaunt": "https://5e.tools/spells.html#kinetic%20jaunt_scc",
  "Knock": "https://5e.tools/spells.html#knock_phb",
  "Legend Lore": "https://5e.tools/spells.html#legend%20lore_phb",
  "Leomund's Secret Chest": "https://5e.tools/spells.html#leomund%27s%20secret%20chest_phb",
  "Leomund's Tiny Hut": "https://5e.tools/spells.html#leomund%27s%20tiny%20hut_phb",
  "Lesser Restoration": "https://5e.tools/spells.html#lesser%20restoration_phb",
  "Levitate": "https://5e.tools/spells.html#levitate_phb",
  "Life Transference": "https://5e.tools/spells.html#life%20transference_xge",
  "Light": "https://5e.tools/spells.html#light_phb",
  "Lightning Arrow": "https://5e.tools/spells.html#lightning%20arrow_phb",
  "Lightning Bolt": "https://5e.tools/spells.html#lightning%20bolt_phb",
  "Lightning Lure": "https://5e.tools/spells.html#lightning%20lure_tce",
  "Locate Animals or Plants": "https://5e.tools/spells.html#locate%20animals%20or%20plants_phb",
  "Locate Creature": "https://5e.tools/spells.html#locate%20creature_phb",
  "Locate Object": "https://5e.tools/spells.html#locate%20object_phb",
  "Longstrider": "https://5e.tools/spells.html#longstrider_phb",
  "Maddening Darkness": "https://5e.tools/spells.html#maddening%20darkness_xge",
  "Maelstrom": "https://5e.tools/spells.html#maelstrom_xge",
  "Mage Armor": "https://5e.tools/spells.html#mage%20armor_phb",
  "Mage Hand": "https://5e.tools/spells.html#mage%20hand_phb",
  "Magic Circle": "https://5e.tools/spells.html#magic%20circle_phb",
  "Magic Jar": "https://5e.tools/spells.html#magic%20jar_phb",
  "Magic Missile": "https://5e.tools/spells.html#magic%20missile_phb",
  "Magic Mouth": "https://5e.tools/spells.html#magic%20mouth_phb",
  "Magic Stone": "https://5e.tools/spells.html#magic%20stone_xge",
  "Magic Weapon": "https://5e.tools/spells.html#magic%20weapon_phb",
  "Major Image": "https://5e.tools/spells.html#major%20image_phb",
  "Mass Cure Wounds": "https://5e.tools/spells.html#mass%20cure%20wounds_phb",
  "Mass Heal": "https://5e.tools/spells.html#mass%20heal_phb",
  "Mass Healing Word": "https://5e.tools/spells.html#mass%20healing%20word_phb",
  "Mass Polymorph": "https://5e.tools/spells.html#mass%20polymorph_xge",
  "Mass Suggestion": "https://5e.tools/spells.html#mass%20suggestion_phb",
  "Maximilian's Earthen Grasp": "https://5e.tools/spells.html#maximilian%27s%20earthen%20grasp_xge",
  "Maze": "https://5e.tools/spells.html#maze_phb",
  "Meld into Stone": "https://5e.tools/spells.html#meld%20into%20stone_phb",
  "Melf's Acid Arrow": "https://5e.tools/spells.html#melf%27s%20acid%20arrow_phb",
  "Melf's Minute Meteors": "https://5e.tools/spells.html#melf%27s%20minute%20meteors_xge",
  "Mending": "https://5e.tools/spells.html#mending_phb",
  "Mental Prison": "https://5e.tools/spells.html#mental%20prison_xge",
  "Message": "https://5e.tools/spells.html#message_phb",
  "Meteor Swarm": "https://5e.tools/spells.html#meteor%20swarm_phb",
  "Mighty Fortress": "https://5e.tools/spells.html#mighty%20fortress_xge",
  "Mind Blank": "https://5e.tools/spells.html#mind%20blank_phb",
  "Mind Sliver": "https://5e.tools/spells.html#mind%20sliver_tce",
  "Mind Spike": "https://5e.tools/spells.html#mind%20spike_xge",
  "Minor Illusion": "https://5e.tools/spells.html#minor%20illusion_phb",
  "Mirage Arcane": "https://5e.tools/spells.html#mirage%20arcane_phb",
  "Mirror Image": "https://5e.tools/spells.html#mirror%20image_phb",
  "Mislead": "https://5e.tools/spells.html#mislead_phb",
  "Misty Step": "https://5e.tools/spells.html#misty%20step_phb",
  "Modify Memory": "https://5e.tools/spells.html#modify%20memory_phb",
  "Mold Earth": "https://5e.tools/spells.html#mold%20earth_xge",
  "Moonbeam": "https://5e.tools/spells.html#moonbeam_phb",
  "Mordenkainen's Faithful Hound": "https://5e.tools/spells.html#mordenkainen%27s%20faithful%20hound_phb",
  "Mordenkainen's Magnificent Mansion": "https://5e.tools/spells.html#mordenkainen%27s%20magnificent%20mansion_phb",
  "Mordenkainen's Private Sanctum": "https://5e.tools/spells.html#mordenkainen%27s%20private%20sanctum_phb",
  "Mordenkainen's Sword": "https://5e.tools/spells.html#mordenkainen%27s%20sword_phb",
  "Motivational Speech": "https://5e.tools/spells.html#motivational%20speech_ai",
  "Move Earth": "https://5e.tools/spells.html#move%20earth_phb",
  "Nathair's Mischief": "https://5e.tools/spells.html#nathair%27s%20mischief_ftd",
  "Negative Energy Flood": "https://5e.tools/spells.html#negative%20energy%20flood_xge",
  "Nondetection": "https://5e.tools/spells.html#nondetection_phb",
  "Nystul's Magic Aura": "https://5e.tools/spells.html#nystul%27s%20magic%20aura_phb",
  "Otiluke's Freezing Sphere": "https://5e.tools/spells.html#otiluke%27s%20freezing%20sphere_phb",
  "Otiluke's Resilient Sphere": "https://5e.tools/spells.html#otiluke%27s%20resilient%20sphere_phb",
  "Otto's Irresistible Dance": "https://5e.tools/spells.html#otto%27s%20irresistible%20dance_phb",
  "Pass without Trace": "https://5e.tools/spells.html#pass%20without%20trace_phb",
  "Passwall": "https://5e.tools/spells.html#passwall_phb",
  "Phantasmal Force": "https://5e.tools/spells.html#phantasmal%20force_phb",
  "Phantasmal Killer": "https://5e.tools/spells.html#phantasmal%20killer_phb",
  "Phantom Steed": "https://5e.tools/spells.html#phantom%20steed_phb",
  "Planar Ally": "https://5e.tools/spells.html#planar%20ally_phb",
  "Planar Binding": "https://5e.tools/spells.html#planar%20binding_phb",
  "Plane Shift": "https://5e.tools/spells.html#plane%20shift_phb",
  "Plant Growth": "https://5e.tools/spells.html#plant%20growth_phb",
  "Poison Spray": "https://5e.tools/spells.html#poison%20spray_phb",
  "Polymorph": "https://5e.tools/spells.html#polymorph_phb",
  "Power Word Heal": "https://5e.tools/spells.html#power%20word%20heal_phb",
  "Power Word Kill": "https://5e.tools/spells.html#power%20word%20kill_phb",
  "Power Word Pain": "https://5e.tools/spells.html#power%20word%20pain_xge",
  "Power Word Stun": "https://5e.tools/spells.html#power%20word%20stun_phb",
  "Prayer of Healing": "https://5e.tools/spells.html#prayer%20of%20healing_phb",
  "Prestidigitation": "https://5e.tools/spells.html#prestidigitation_phb",
  "Primal Savagery": "https://5e.tools/spells.html#primal%20savagery_xge",
  "Primordial Ward": "https://5e.tools/spells.html#primordial%20ward_xge",
  "Prismatic Spray": "https://5e.tools/spells.html#prismatic%20spray_phb",
  "Prismatic Wall": "https://5e.tools/spells.html#prismatic%20wall_phb",
  "Produce Flame": "https://5e.tools/spells.html#produce%20flame_phb",
  "Programmed Illusion": "https://5e.tools/spells.html#programmed%20illusion_phb",
  "Project Image": "https://5e.tools/spells.html#project%20image_phb",
  "Protection from Energy": "https://5e.tools/spells.html#protection%20from%20energy_phb",
  "Protection from Evil and Good": "https://5e.tools/spells.html#protection%20from%20evil%20and%20good_phb",
  "Protection from Poison": "https://5e.tools/spells.html#protection%20from%20poison_phb",
  "Psychic Scream": "https://5e.tools/spells.html#psychic%20scream_xge",
  "Purify Food and Drink": "https://5e.tools/spells.html#purify%20food%20and%20drink_phb",
  "Pyrotechnics": "https://5e.tools/spells.html#pyrotechnics_xge",
  "Raise Dead": "https://5e.tools/spells.html#raise%20dead_phb",
  "Rary's Telepathic Bond": "https://5e.tools/spells.html#rary%27s%20telepathic%20bond_phb",
  "Raulothim's Psychic Lance": "https://5e.tools/spells.html#raulothim%27s%20psychic%20lance_ftd",
  "Ray of Enfeeblement": "https://5e.tools/spells.html#ray%20of%20enfeeblement_phb",
  "Ray of Frost": "https://5e.tools/spells.html#ray%20of%20frost_phb",
  "Ray of Sickness": "https://5e.tools/spells.html#ray%20of%20sickness_phb",
  "Regenerate": "https://5e.tools/spells.html#regenerate_phb",
  "Reincarnate": "https://5e.tools/spells.html#reincarnate_phb",
  "Remove Curse": "https://5e.tools/spells.html#remove%20curse_phb",
  "Resistance": "https://5e.tools/spells.html#resistance_phb",
  "Resurrection": "https://5e.tools/spells.html#resurrection_phb",
  "Reverse Gravity": "https://5e.tools/spells.html#reverse%20gravity_phb",
  "Revivify": "https://5e.tools/spells.html#revivify_phb",
  "Rime's Binding Ice": "https://5e.tools/spells.html#rime%27s%20binding%20ice_ftd",
  "Rope Trick": "https://5e.tools/spells.html#rope%20trick_phb",
  "Sacred Flame": "https://5e.tools/spells.html#sacred%20flame_phb",
  "Sanctuary": "https://5e.tools/spells.html#sanctuary_phb",
  "Scatter": "https://5e.tools/spells.html#scatter_xge",
  "Scorching Ray": "https://5e.tools/spells.html#scorching%20ray_phb",
  "Scrying": "https://5e.tools/spells.html#scrying_phb",
  "Searing Smite": "https://5e.tools/spells.html#searing%20smite_phb",
  "See Invisibility": "https://5e.tools/spells.html#see%20invisibility_phb",
  "Seeming": "https://5e.tools/spells.html#seeming_phb",
  "Sending": "https://5e.tools/spells.html#sending_phb",
  "Sequester": "https://5e.tools/spells.html#sequester_phb",
  "Shadow Blade": "https://5e.tools/spells.html#shadow%20blade_xge",
  "Shadow of Moil": "https://5e.tools/spells.html#shadow%20of%20moil_xge",
  "Shape Water": "https://5e.tools/spells.html#shape%20water_xge",
  "Shapechange": "https://5e.tools/spells.html#shapechange_phb",
  "Shatter": "https://5e.tools/spells.html#shatter_phb",
  "Shield": "https://5e.tools/spells.html#shield_phb",
  "Shield of Faith": "https://5e.tools/spells.html#shield%20of%20faith_phb",
  "Shillelagh": "https://5e.tools/spells.html#shillelagh_phb",
  "Shocking Grasp": "https://5e.tools/spells.html#shocking%20grasp_phb",
  "Sickening Radiance": "https://5e.tools/spells.html#sickening%20radiance_xge",
  "Silence": "https://5e.tools/spells.html#silence_phb",
  "Silent Image": "https://5e.tools/spells.html#silent%20image_phb",
  "Silvery Barbs": "https://5e.tools/spells.html#silvery%20barbs_scc",
  "Simulacrum": "https://5e.tools/spells.html#simulacrum_phb",
  "Skill Empowerment": "https://5e.tools/spells.html#skill%20empowerment_xge",
  "Skywrite": "https://5e.tools/spells.html#skywrite_xge",
  "Sleep": "https://5e.tools/spells.html#sleep_phb",
  "Sleet Storm": "https://5e.tools/spells.html#sleet%20storm_phb",
  "Slow": "https://5e.tools/spells.html#slow_phb",
  "Snare": "https://5e.tools/spells.html#snare_xge",
  "Snilloc's Snowball Swarm": "https://5e.tools/spells.html#snilloc%27s%20snowball%20swarm_xge",
  "Soul Cage": "https://5e.tools/spells.html#soul%20cage_xge",
  "Spare the Dying": "https://5e.tools/spells.html#spare%20the%20dying_phb",
  "Speak with Animals": "https://5e.tools/spells.html#speak%20with%20animals_phb",
  "Speak with Dead": "https://5e.tools/spells.html#speak%20with%20dead_phb",
  "Speak with Plants": "https://5e.tools/spells.html#speak%20with%20plants_phb",
  "Spider Climb": "https://5e.tools/spells.html#spider%20climb_phb",
  "Spike Growth": "https://5e.tools/spells.html#spike%20growth_phb",
  "Spirit Guardians": "https://5e.tools/spells.html#spirit%20guardians_phb",
  "Spirit of Death": "https://5e.tools/spells.html#spirit%20of%20death_bmt",
  "Spirit Shroud": "https://5e.tools/spells.html#spirit%20shroud_tce",
  "Spiritual Weapon": "https://5e.tools/spells.html#spiritual%20weapon_phb",
  "Spray of Cards": "https://5e.tools/spells.html#spray%20of%20cards_bmt",
  "Staggering Smite": "https://5e.tools/spells.html#staggering%20smite_phb",
  "Steel Wind Strike": "https://5e.tools/spells.html#steel%20wind%20strike_xge",
  "Stinking Cloud": "https://5e.tools/spells.html#stinking%20cloud_phb",
  "Stone Shape": "https://5e.tools/spells.html#stone%20shape_phb",
  "Stoneskin": "https://5e.tools/spells.html#stoneskin_phb",
  "Storm of Vengeance": "https://5e.tools/spells.html#storm%20of%20vengeance_phb",
  "Storm Sphere": "https://5e.tools/spells.html#storm%20sphere_xge",
  "Suggestion": "https://5e.tools/spells.html#suggestion_phb",
  "Summon Aberration": "https://5e.tools/spells.html#summon%20aberration_tce",
  "Summon Beast": "https://5e.tools/spells.html#summon%20beast_tce",
  "Summon Celestial": "https://5e.tools/spells.html#summon%20celestial_tce",
  "Summon Construct": "https://5e.tools/spells.html#summon%20construct_tce",
  "Summon Draconic Spirit": "https://5e.tools/spells.html#summon%20draconic%20spirit_ftd",
  "Summon Elemental": "https://5e.tools/spells.html#summon%20elemental_tce",
  "Summon Fey": "https://5e.tools/spells.html#summon%20fey_tce",
  "Summon Fiend": "https://5e.tools/spells.html#summon%20fiend_tce",
  "Summon Greater Demon": "https://5e.tools/spells.html#summon%20greater%20demon_xge",
  "Summon Lesser Demons": "https://5e.tools/spells.html#summon%20lesser%20demons_xge",
  "Summon Shadowspawn": "https://5e.tools/spells.html#summon%20shadowspawn_tce",
  "Summon Undead": "https://5e.tools/spells.html#summon%20undead_tce",
  "Sunbeam": "https://5e.tools/spells.html#sunbeam_phb",
  "Sunburst": "https://5e.tools/spells.html#sunburst_phb",
  "Swift Quiver": "https://5e.tools/spells.html#swift%20quiver_phb",
  "Sword Burst": "https://5e.tools/spells.html#sword%20burst_tce",
  "Symbol": "https://5e.tools/spells.html#symbol_phb",
  "Synaptic Static": "https://5e.tools/spells.html#synaptic%20static_xge",
  "Tasha's Caustic Brew": "https://5e.tools/spells.html#tasha%27s%20caustic%20brew_tce",
  "Tasha's Hideous Laughter": "https://5e.tools/spells.html#tasha%27s%20hideous%20laughter_phb",
  "Tasha's Mind Whip": "https://5e.tools/spells.html#tasha%27s%20mind%20whip_tce",
  "Tasha's Otherworldly Guise": "https://5e.tools/spells.html#tasha%27s%20otherworldly%20guise_tce",
  "Telekinesis": "https://5e.tools/spells.html#telekinesis_phb",
  "Telepathy": "https://5e.tools/spells.html#telepathy_phb",
  "Teleport": "https://5e.tools/spells.html#teleport_phb",
  "Teleportation Circle": "https://5e.tools/spells.html#teleportation%20circle_phb",
  "Temple of the Gods": "https://5e.tools/spells.html#temple%20of%20the%20gods_xge",
  "Tenser's Floating Disk": "https://5e.tools/spells.html#tenser%27s%20floating%20disk_phb",
  "Tenser's Transformation": "https://5e.tools/spells.html#tenser%27s%20transformation_xge",
  "Thaumaturgy": "https://5e.tools/spells.html#thaumaturgy_phb",
  "Thorn Whip": "https://5e.tools/spells.html#thorn%20whip_phb",
  "Thunder Step": "https://5e.tools/spells.html#thunder%20step_xge",
  "Thunderclap": "https://5e.tools/spells.html#thunderclap_xge",
  "Thunderous Smite": "https://5e.tools/spells.html#thunderous%20smite_phb",
  "Thunderwave": "https://5e.tools/spells.html#thunderwave_phb",
  "Tidal Wave": "https://5e.tools/spells.html#tidal%20wave_xge",
  "Time Stop": "https://5e.tools/spells.html#time%20stop_phb",
  "Tiny Servant": "https://5e.tools/spells.html#tiny%20servant_xge",
  "Toll the Dead": "https://5e.tools/spells.html#toll%20the%20dead_xge",
  "Tongues": "https://5e.tools/spells.html#tongues_phb",
  "Transmute Rock": "https://5e.tools/spells.html#transmute%20rock_xge",
  "Transport via Plants": "https://5e.tools/spells.html#transport%20via%20plants_phb",
  "Tree Stride": "https://5e.tools/spells.html#tree%20stride_phb",
  "True Polymorph": "https://5e.tools/spells.html#true%20polymorph_phb",
  "True Resurrection": "https://5e.tools/spells.html#true%20resurrection_phb",
  "True Seeing": "https://5e.tools/spells.html#true%20seeing_phb",
  "True Strike": "https://5e.tools/spells.html#true%20strike_phb",
  "Tsunami": "https://5e.tools/spells.html#tsunami_phb",
  "Unseen Servant": "https://5e.tools/spells.html#unseen%20servant_phb",
  "Vampiric Touch": "https://5e.tools/spells.html#vampiric%20touch_phb",
  "Vicious Mockery": "https://5e.tools/spells.html#vicious%20mockery_phb",
  "Vitriolic Sphere": "https://5e.tools/spells.html#vitriolic%20sphere_xge",
  "Vortex Warp": "https://5e.tools/spells.html#vortex%20warp_scc",
  "Wall of Fire": "https://5e.tools/spells.html#wall%20of%20fire_phb",
  "Wall of Force": "https://5e.tools/spells.html#wall%20of%20force_phb",
  "Wall of Ice": "https://5e.tools/spells.html#wall%20of%20ice_phb",
  "Wall of Light": "https://5e.tools/spells.html#wall%20of%20light_xge",
  "Wall of Sand": "https://5e.tools/spells.html#wall%20of%20sand_xge",
  "Wall of Stone": "https://5e.tools/spells.html#wall%20of%20stone_phb",
  "Wall of Thorns": "https://5e.tools/spells.html#wall%20of%20thorns_phb",
  "Wall of Water": "https://5e.tools/spells.html#wall%20of%20water_xge",
  "Warding Bond": "https://5e.tools/spells.html#warding%20bond_phb",
  "Warding Wind": "https://5e.tools/spells.html#warding%20wind_xge",
  "Warp Sense": "https://5e.tools/spells.html#warp%20sense_sato",
  "Water Breathing": "https://5e.tools/spells.html#water%20breathing_phb",
  "Water Walk": "https://5e.tools/spells.html#water%20walk_phb",
  "Watery Sphere": "https://5e.tools/spells.html#watery%20sphere_xge",
  "Web": "https://5e.tools/spells.html#web_phb",
  "Weird": "https://5e.tools/spells.html#weird_phb",
  "Whirlwind": "https://5e.tools/spells.html#whirlwind_xge",
  "Wind Walk": "https://5e.tools/spells.html#wind%20walk_phb",
  "Wind Wall": "https://5e.tools/spells.html#wind%20wall_phb",
  "Wish": "https://5e.tools/spells.html#wish_phb",
  "Witch Bolt": "https://5e.tools/spells.html#witch%20bolt_phb",
  "Wither and Bloom": "https://5e.tools/spells.html#wither%20and%20bloom_scc",
  "Word of Radiance": "https://5e.tools/spells.html#word%20of%20radiance_xge",
  "Word of Recall": "https://5e.tools/spells.html#word%20of%20recall_phb",
  "Wrath of Nature": "https://5e.tools/spells.html#wrath%20of%20nature_xge",
  "Wrathful Smite": "https://5e.tools/spells.html#wrathful%20smite_phb",
  "Zephyr Strike": "https://5e.tools/spells.html#zephyr%20strike_xge",
  "Zone of Truth": "https://5e.tools/spells.html#zone%20of%20truth_phb"
};

function addSpellToStatBlock(spellName){
    let spellLink = spellUrls[spellName];
    if(spellLink){
        return `<a href="${spellLink}" target="_blank">${spellName}</a>`;
    }else{
        return spellName; // Fallback if the spell isn't in the map
    }
}
